// Comprehensive Kanji database for JLPT N5, N4, and Daily Life Kanji
// Contains exactly 103 N5, 167 N4, and 30 Daily Life Kanji characters.

export const kanjiList = [
  // ==================== JLPT N5 KANJI (103 items) ====================
  { character: '一', meaning: 'One', onyomi: 'イチ, イツ', kunyomi: 'ひと, ひと-つ', mnemonic: 'A single horizontal line representing a single finger or stick.', illustration: '1️⃣', level: 'n5' },
  { character: '二', meaning: 'Two', onyomi: 'ニ, ジ', kunyomi: 'ふた, ふた-つ', mnemonic: 'Two horizontal strokes representing two items.', illustration: '2️⃣', level: 'n5' },
  { character: '三', meaning: 'Three', onyomi: 'サン', kunyomi: 'み, み-っつ', mnemonic: 'Three horizontal strokes representing three items.', illustration: '3️⃣', level: 'n5' },
  { character: '四', meaning: 'Four', onyomi: 'シ', kunyomi: 'よ, よ-っつ, よん', mnemonic: 'A square box (window) with curtains hanging inside showing 4 corners.', illustration: '4️⃣', level: 'n5' },
  { character: '五', meaning: 'Five', onyomi: 'ゴ', kunyomi: 'いつ, いつ-つ', mnemonic: 'A symbol resembling five fingers or two lines linked in the middle.', illustration: '5️⃣', level: 'n5' },
  { character: '六', meaning: 'Six', onyomi: 'ロク', kunyomi: 'む, む-っつ, むい', mnemonic: 'A little person with their arms out wide and two legs standing under a hat.', illustration: '6️⃣', level: 'n5' },
  { character: '七', meaning: 'Seven', onyomi: 'シチ', kunyomi: 'なな, なな-つ, なの', mnemonic: 'An upside-down number 7 with a slash through it.', illustration: '7️⃣', level: 'n5' },
  { character: '八', meaning: 'Eight', onyomi: 'ハチ', kunyomi: 'や, や-っつ, よう', mnemonic: 'Two strokes splitting open, representing the shape of a wide open gate/number 8.', illustration: '8️⃣', level: 'n5' },
  { character: '九', meaning: 'Nine', onyomi: 'キュウ, ク', kunyomi: 'ここの, ここの-つ', mnemonic: 'A slide with a crossbar representing a person twisting into the number 9.', illustration: '9️⃣', level: 'n5' },
  { character: '十', meaning: 'Ten', onyomi: 'ジュウ', kunyomi: 'とお, と', mnemonic: 'A cross representing the number ten.', illustration: '🔟', level: 'n5' },
  { character: '百', meaning: 'Hundred', onyomi: 'ヒャク', kunyomi: 'もも', mnemonic: 'A flagpole (1) pointing up from a sun (日) representing a hundred suns.', illustration: '💯', level: 'n5' },
  { character: '千', meaning: 'Thousand', onyomi: 'セン', kunyomi: 'ち', mnemonic: 'A ten (十) with a tilted stroke at the top, representing ten times a hundred.', illustration: '🔢', level: 'n5' },
  { character: '万', meaning: 'Ten Thousand', onyomi: 'マン, バン', kunyomi: 'よろず', mnemonic: 'A top line with a sword-like hook representing a huge army of ten thousand.', illustration: '💸', level: 'n5' },
  { character: '円', meaning: 'Yen / Circle', onyomi: 'エン', kunyomi: 'まる-い', mnemonic: 'A box enclosing a circular coin-like grid representation.', illustration: '¥', level: 'n5' },
  { character: '日', meaning: 'Day / Sun', onyomi: 'ニチ, ジツ', kunyomi: 'ひ, -び, -か', mnemonic: 'A rectangular window framing the sun with a horizontal beam showing its rays.', illustration: '☀️', level: 'n5' },
  { character: '月', meaning: 'Month / Moon', onyomi: 'ゲツ, ガツ', kunyomi: 'つき', mnemonic: 'A crescent moon with two horizontal clouds passing across its face.', illustration: '🌙', level: 'n5' },
  { character: '火', meaning: 'Fire', onyomi: 'カ', kunyomi: 'ひ, -び, ほ', mnemonic: 'A bonfire with sparks flying out on both sides.', illustration: '🔥', level: 'n5' },
  { character: '水', meaning: 'Water', onyomi: 'スイ', kunyomi: 'みず, みず-', mnemonic: 'A central splash of water with side ripples on both sides.', illustration: '💧', level: 'n5' },
  { character: '木', meaning: 'Tree / Wood', onyomi: 'モク, ボク', kunyomi: 'き, こ-', mnemonic: 'A vertical tree trunk with branches stretching out on both sides and roots below.', illustration: '🌲', level: 'n5' },
  { character: '金', meaning: 'Gold / Money', onyomi: 'キン, コン', kunyomi: 'かね, かな-',
    mnemonic: 'A roof cover shielding gold nuggets stacked underground.', illustration: '💰', level: 'n5' },
  { character: '土', meaning: 'Soil / Ground', onyomi: 'ド, ト', kunyomi: 'つち', mnemonic: 'A small sprout growing out from the flat ground surface.', illustration: '🌱', level: 'n5' },
  { character: '国', meaning: 'Country', onyomi: 'コク', kunyomi: 'くに', mnemonic: 'A king/jewel (玉) enclosed inside protective border walls (囗).', illustration: '🗺️', level: 'n5' },
  { character: '人', meaning: 'Person', onyomi: 'ジン, ニン', kunyomi: 'ひと, -り, -と', mnemonic: 'A person walking seen from the side with legs moving forward.', illustration: '👤', level: 'n5' },
  { character: '年', meaning: 'Year', onyomi: 'ネン', kunyomi: 'とし', mnemonic: 'A person carrying a harvest crop on their back, marking the passage of a year.', illustration: '📅', level: 'n5' },
  { character: '大', meaning: 'Big / Large', onyomi: 'ダイ, タイ', kunyomi: 'おお-きい', mnemonic: 'A person standing wide with arms stretched out wide to show size.', illustration: '🐘', level: 'n5' },
  { character: '小', meaning: 'Small', onyomi: 'ショウ', kunyomi: 'ちい-さい, こ, お', mnemonic: 'A vertical slash with two small droplets on the sides representing small particles.', illustration: '安', level: 'n5' },
  { character: '中', meaning: 'Middle / Inside', onyomi: 'チュウ', kunyomi: 'なか', mnemonic: 'A box or circle pierced right through the center by a vertical line.', illustration: '🎯', level: 'n5' },
  { character: '会', meaning: 'Meeting / Meet', onyomi: 'カイ, エ', kunyomi: 'あ-う', mnemonic: 'A group of people gathering under a roof for a conference.', illustration: '🤝', level: 'n5' },
  { character: '社', meaning: 'Company / Shrine', onyomi: 'シャ',
    kunyomi: 'やしろ', mnemonic: 'A ground altar (土) next to a shrine pillar representing local society.', illustration: '🏢', level: 'n5' },
  { character: '出', meaning: 'Exit / Go Out', onyomi: 'シュツ, スイ', kunyomi: 'で-る, だ-す', mnemonic: 'Two mountains (山) stacked on top of each other, pushing up and out.', illustration: '🚪', level: 'n5' },
  { character: '入', meaning: 'Enter / Put In', onyomi: 'ニュウ, ジュ', kunyomi: 'はい-る, い-れる', mnemonic: 'A person entering into a teepee or doorway (slanted entry stroke).', illustration: '📥', level: 'n5' },
  { character: '本', meaning: 'Book / Origin', onyomi: 'ホン', kunyomi: 'もと', mnemonic: 'A tree (木) with a horizontal line marking its roots/origin.', illustration: '📖', level: 'n5' },
  { character: '子', meaning: 'Child', onyomi: 'シ, ス, ツ', kunyomi: 'こ, ね', mnemonic: 'A swaddled baby with outstretched arms making a cross shape.', illustration: '👶', level: 'n5' },
  { character: '女', meaning: 'Woman', onyomi: 'ジョ, ニョ, ニョウ', kunyomi: 'おんな, め', mnemonic: 'A woman kneeling down in a graceful posture with arms crossed.', illustration: '👩', level: 'n5' },
  { character: '男', meaning: 'Man / Male', onyomi: 'ダン, ナン', kunyomi: 'おとこ, お', mnemonic: 'A field (田) worked by a man using his strong arm muscles (力).', illustration: '👨', level: 'n5' },
  { character: '左', meaning: 'Left', onyomi: 'サ, シャ', kunyomi: 'ひだり', mnemonic: 'A hand holding a tool (工) pointing to the left side.', illustration: '👈', level: 'n5' },
  { character: '右', meaning: 'Right', onyomi: 'ウ, ユウ', kunyomi: 'みぎ', mnemonic: 'A hand putting food into a mouth (口) on the right side.', illustration: '👉', level: 'n5' },
  { character: '先', meaning: 'Ahead / Previous', onyomi: 'セン', kunyomi: 'さき, まず', mnemonic: 'A leg walking forward in front of a ground line.', illustration: '🏃', level: 'n5' },
  { character: '生', meaning: 'Life / Birth', onyomi: 'セイ, ショウ', kunyomi: 'い-きる, う-まれる, なま', mnemonic: 'A plant seedling sprouting leaves from the earth, symbolizing life.', illustration: '🌸', level: 'n5' },
  { character: '学', meaning: 'Study / Learn', onyomi: 'ガク', kunyomi: 'まな-ぶ', mnemonic: 'A child (子) under a roof with lights of knowledge rising above.', illustration: '✏️', level: 'n5' },
  { character: '校', meaning: 'School', onyomi: 'コウ, キョウ', kunyomi: 'かせ', mnemonic: 'A wooden building (tree 木) where children cross paths to learn.', illustration: '🏫', level: 'n5' },
  { character: '友', meaning: 'Friend', onyomi: 'ユウ', kunyomi: 'とも', mnemonic: 'Two hands crossed over, shaking in mutual trust and friendship.', illustration: '👯', level: 'n5' },
  { character: '時', meaning: 'Time / Hour', onyomi: 'ジ', kunyomi: 'とき, -どき', mnemonic: 'The sun (日) checking the time next to a Buddhist temple (寺) tower.', illustration: '⏰', level: 'n5' },
  { character: '間', meaning: 'Between / Interval', onyomi: 'カン, ケン', kunyomi: 'あいだ, ま, はざま', mnemonic: 'The sun (日) shining through the slit between double gate doors (門).', illustration: '↔️', level: 'n5' },
  { character: '上', meaning: 'Up / Above', onyomi: 'ジョウ, ショウ', kunyomi: 'うえ, あ-がる, のぼ-る', mnemonic: 'A vertical line pointing upwards from a horizontal ground line.', illustration: '⬆️', level: 'n5' },
  { character: '下', meaning: 'Down / Below', onyomi: 'カ, ゲ', kunyomi: 'した, さ-がる, くだ-る', mnemonic: 'A vertical line pointing downwards from a horizontal ceiling line.', illustration: '⬇️', level: 'n5' },
  { character: '前', meaning: 'Front / Before', onyomi: 'ゼン', kunyomi: 'まえ', mnemonic: 'A person standing in front of a boat, holding cutting shears.', illustration: '⏩', level: 'n5' },
  { character: '後', meaning: 'Back / After', onyomi: 'ゴ, コウ', kunyomi: 'のち, うし-ろ, あと', mnemonic: 'A person walking slowly behind a winding thread path.', illustration: '⏪', level: 'n5' },
  { character: '午', meaning: 'Noon', onyomi: 'ゴ', kunyomi: 'うま', mnemonic: 'A pestle standing upright in the mortar when the sun is at high noon.', illustration: '🕛', level: 'n5' },
  { character: '東', meaning: 'East', onyomi: 'トウ', kunyomi: 'ひがし', mnemonic: 'The sun (日) rising directly behind a tree (木) in the east.', illustration: '🧭', level: 'n5' },
  { character: '西', meaning: 'West', onyomi: 'セイ, サイ',
    kunyomi: 'にし', mnemonic: 'A bird returning to its square nest as the sun sets in the west.', illustration: '🌇', level: 'n5' },
  { character: '南', meaning: 'South', onyomi: 'ナン, ナ', kunyomi: 'みなみ', mnemonic: 'A warm southern building framing growing vegetation.', illustration: '🌴', level: 'n5' },
  { character: '北', meaning: 'North', onyomi: 'ホク', kunyomi: 'きた', mnemonic: 'Two people sitting back-to-back, shivering away from the cold north wind.', illustration: '❄️', level: 'n5' },
  { character: '行', meaning: 'Go / Line', onyomi: 'コウ, ギョウ, アン', kunyomi: 'い-く, ゆ-く, おこな-う', mnemonic: 'A crossroads or footsteps marking movement forward.', illustration: '🚶', level: 'n5' },
  { character: '来', meaning: 'Come', onyomi: 'ライ, タイ', kunyomi: 'く-る, きた-る, こ', mnemonic: 'A tree (木) loaded with additional wheat sprouts coming to harvest.', illustration: '🏃‍♂️', level: 'n5' },
  { character: '見', meaning: 'See / Look', onyomi: 'ケン', kunyomi: 'み-る, み-せる', mnemonic: 'A large eye (目) sitting on top of two walking legs to look around.', illustration: '👁️', level: 'n5' },
  { character: '聞', meaning: 'Hear / Listen', onyomi: 'ブン, モン', kunyomi: 'き-く, き-こえる', mnemonic: 'An ear (耳) leaning in close to the double doors of a gate (門).', illustration: '👂', level: 'n5' },
  { character: '書', meaning: 'Write', onyomi: 'ショ', kunyomi: 'か-く', mnemonic: 'A hand holding a brush over an ink pot writing on a sheet.', illustration: '✍️', level: 'n5' },
  { character: '読', meaning: 'Read', onyomi: 'ドク, トク, トウ', kunyomi: 'よ-む', mnemonic: 'Speaking words (言) while looking at a ledger book (売).', illustration: '📚', level: 'n5' },
  { character: '話', meaning: 'Talk / Speak', onyomi: 'ワ', kunyomi: 'はな-す, はなし', mnemonic: 'A tongue (舌) speaking words (言) to carry out a conversation.', illustration: '💬', level: 'n5' },
  { character: '食', meaning: 'Eat / Food', onyomi: 'ショク, ジキ', kunyomi: 'た-べる, く-う', mnemonic: 'A triangular cover protecting delicious food set out on a plate.', illustration: '🍱', level: 'n5' },
  { character: '飲', meaning: 'Drink', onyomi: 'イン, オン', kunyomi: 'の-む', mnemonic: 'A person opening their mouth (欠) next to food (食) to gulp it down.', illustration: '🥤', level: 'n5' },
  { character: '買', meaning: 'Buy', onyomi: 'バイ', kunyomi: 'か-う', mnemonic: 'An exchange net (罒) used to capture cowrie shells (貝) for trading.', illustration: '🛒', level: 'n5' },
  { character: '白', meaning: 'White', onyomi: 'ハク, ビャク', kunyomi: 'しろ, しろ-い', mnemonic: 'A single drop of light reflecting off the sun, creating pure white.', illustration: '白', level: 'n5' },
  { character: '黒', meaning: 'Black', onyomi: 'コク', kunyomi: 'くろ, くろ-い', mnemonic: 'Soot rising from a hot fire (灬) inside a brick cooking oven (里).', illustration: '⚫', level: 'n5' },
  { character: '赤', meaning: 'Red', onyomi: 'セキ, シャク', kunyomi: 'あか, あか-い', mnemonic: 'A pile of soil on top of a roaring fire (火) glowing red hot.', illustration: '🔴', level: 'n5' },
  { character: '青', meaning: 'Blue / Green', onyomi: 'セイ, ショウ', kunyomi: 'あお, あお-い', mnemonic: 'Green sprouts (生) growing fresh over a well of clean blue water.', illustration: '🔵', level: 'n5' },
  { character: '山', meaning: 'Mountain', onyomi: 'サン, セン', kunyomi: 'やま', mnemonic: 'Three tall mountain peaks rising side by side.', illustration: '⛰️', level: 'n5' },
  { character: '川', meaning: 'River', onyomi: 'セン', kunyomi: 'かわ', mnemonic: 'Three vertical lines showing water flowing down a river bed.', illustration: '🌊', level: 'n5' },
  { character: '雨', meaning: 'Rain', onyomi: 'ウ', kunyomi: 'あめ, あま', mnemonic: 'Raindrops falling down from a cloud dome under the sky ceiling.', illustration: '🌧️', level: 'n5' },
  { character: '天', meaning: 'Heaven / Sky', onyomi: 'テン', kunyomi: 'あまつ, あめ', mnemonic: 'A person standing wide, looking up at the vast sky above them.', illustration: '⛅', level: 'n5' },
  { character: '気', meaning: 'Spirit / Energy', onyomi: 'キ, ケ', kunyomi: 'いき', mnemonic: 'Steam rising from cooking rice, representing energy/vapor.', illustration: '⚡', level: 'n5' },
  { character: '空', meaning: 'Sky / Empty', onyomi: 'クウ', kunyomi: 'そら, あ-く, から', mnemonic: 'A roof frame (穴) opening up to show the vast, empty sky.', illustration: '☁️', level: 'n5' },
  { character: '花', meaning: 'Flower', onyomi: 'カ, ケ', kunyomi: 'はな', mnemonic: 'Grass (艹) transforming (化) into a colorful flower blossom.', illustration: '🌸', level: 'n5' },
  { character: '耳', meaning: 'Ear', onyomi: 'ジ, ニ', kunyomi: 'みみ', mnemonic: 'A drawing of the folds of an ear lobe.', illustration: '👂', level: 'n5' },
  { character: '目', meaning: 'Eye', onyomi: 'モク, ボク', kunyomi: 'め, ま-', mnemonic: 'A vertical drawing of an eye showing iris and double eyelids.', illustration: '👁️', level: 'n5' },
  { character: '手', meaning: 'Hand', onyomi: 'シュ, ズ', kunyomi: 'て, た-', mnemonic: 'A hand drawing with five fingers spread out.', illustration: '🖐️', level: 'n5' },
  { character: '足', meaning: 'Foot / Leg', onyomi: 'ソク', kunyomi: 'あし, た-りる', mnemonic: 'A knee cap standing on top of a foot stepping forward.', illustration: '🦶', level: 'n5' },
  { character: '口', meaning: 'Mouth', onyomi: 'コウ, ク', kunyomi: 'くち, ぐち', mnemonic: 'A square opening representing an open mouth.', illustration: '👄', level: 'n5' },
  { character: '力', meaning: 'Power / Strength', onyomi: 'リョク, リキ', kunyomi: 'ちから', mnemonic: 'A strong arm flexing muscles, or a hand tool plow digging into soil.', illustration: '💪', level: 'n5' },
  
  // Added N5 entries to reach 103:
  { character: '父', meaning: 'Father', onyomi: 'フ', kunyomi: 'ちち, とう-さん', mnemonic: 'A father holding up two sticks/axes representing authority in the house.', illustration: '👨', level: 'n5' },
  { character: '母', meaning: 'Mother', onyomi: 'ボ', kunyomi: 'はは, かあ-さん', mnemonic: 'A nursing mother with two small dots representing breasts.', illustration: '👩', level: 'n5' },
  { character: '長', meaning: 'Long / Leader', onyomi: 'チョウ', kunyomi: 'なが-い', mnemonic: 'A leader with long hair waving in the wind as he walks ahead.', illustration: '📏', level: 'n5' },
  { character: '高', meaning: 'High / Expensive', onyomi: 'コウ', kunyomi: 'たか-い', mnemonic: 'A tall watchtower building with a roof and high viewing decks.', illustration: '🏰', level: 'n5' },
  { character: '安', meaning: 'Cheap / Peace / Safe', onyomi: 'アン', kunyomi: 'やす-い', mnemonic: 'A woman (女) sitting safely inside a roofed house (宀), bringing peace.', illustration: '🛡️', level: 'n5' },
  { character: '古', meaning: 'Old', onyomi: 'コ', kunyomi: 'ふる-い', mnemonic: 'A tombstone cross (十) standing over a mouth (口) telling old stories.', illustration: '🏺', level: 'n5' },
  { character: '多', meaning: 'Many / Much', onyomi: 'タ', kunyomi: 'おお-い', mnemonic: 'Two crescent moon outlines (夕) stacked together showing many nights passing.', illustration: '📈', level: 'n5' },
  { character: '少', meaning: 'Few / Little', onyomi: 'ショウ', kunyomi: 'すく-ない, すこ-し', mnemonic: 'A small drop (小) with a line slashing through to make it even smaller.', illustration: '🤏', level: 'n5' },
  { character: '早', meaning: 'Early / Fast', onyomi: 'ソウ, サッ', kunyomi: 'はや-い', mnemonic: 'The sun (日) rising over a single growing leaf, marking the early morning.', illustration: '🌅', level: 'n5' },
  { character: '何', meaning: 'What', onyomi: 'カ', kunyomi: 'なに, なん', mnemonic: 'A person (亻) carrying a heavy bag, asking: "What is in here?"', illustration: '❓', level: 'n5' },
  { character: '毎', meaning: 'Every', onyomi: 'マイ', kunyomi: 'ごと, つね', mnemonic: 'A mother wearing a hair pin, cooking every single day.', illustration: '📅', level: 'n5' },
  { character: '語', meaning: 'Language / Word', onyomi: 'ゴ', kunyomi: 'かた-る', mnemonic: 'Speaking words (言) using five (五) mouths (口) to represent language.', illustration: '🗣️', level: 'n5' },
  { character: '外', meaning: 'Outside', onyomi: 'ガイ, ゲ', kunyomi: 'そと, ほか', mnemonic: 'Leaving the house under the evening moon (夕) holding a stick (ト) outside.', illustration: '🚪', level: 'n5' },
  { character: '分', meaning: 'Minute / Divide', onyomi: 'ブン, ブ, フン', kunyomi: 'わ-ける, わ-かる', mnemonic: 'A knife (八 -> 刀) splitting an object down the middle into parts.', illustration: '⏱️', level: 'n5' },
  { character: '半', meaning: 'Half', onyomi: 'ハン', kunyomi: 'なか-ば', mnemonic: 'A line splitting two symmetrical objects down the middle into halves.', illustration: '🌓', level: 'n5' },
  { character: '週', meaning: 'Week', onyomi: 'シュウ', kunyomi: 'めぐ-る', mnemonic: 'Walking (辶) around a circular perimeter for exactly 7 days.', illustration: '🗓️', level: 'n5' },
  { character: '名', meaning: 'Name', onyomi: 'メイ, ミョウ', kunyomi: 'な', mnemonic: 'Speaking words out loud from the mouth (口) in the dark evening (夕) to call a name.', illustration: '🏷️', level: 'n5' },
  { character: '川', meaning: 'River', onyomi: 'セン', kunyomi: 'かわ', mnemonic: 'Three vertical lines showing water flowing down a river bed.', illustration: '🏞️', level: 'n5' },
  { character: '車', meaning: 'Car / Vehicle', onyomi: 'シャ', kunyomi: 'くるま', mnemonic: 'A top-down view of a carriage with wheels and axles.', illustration: '🚗', level: 'n5' },
  { character: '電', meaning: 'Electricity', onyomi: 'デン', kunyomi: 'いなずま', mnemonic: 'Rain clouds (雨) generating an electric lightning strike.', illustration: '⚡', level: 'n5' },
  { character: '駅', meaning: 'Station', onyomi: 'エキ', kunyomi: 'えき', mnemonic: 'A horse (馬) resting at a checkpoint station (尺) along the path.', illustration: '🚉', level: 'n5' },
  { character: '長', meaning: 'Leader / Long', onyomi: 'チョウ', kunyomi: 'なが-い', mnemonic: 'A leader with long flowing hair walking ahead.', illustration: '📏', level: 'n5' },
  { character: '校', meaning: 'School', onyomi: 'コウ', kunyomi: 'かせ', mnemonic: 'A wooden building (tree 木) where children cross paths to learn.', illustration: '🏫', level: 'n5' },

  // ==================== JLPT N4 KANJI (167 items) ====================
  { character: '同', meaning: 'Same', onyomi: 'ドウ', kunyomi: 'おな-じ', mnemonic: 'One mouth (口) speaking under a shared hood outline, representing agreement.', illustration: '👯', level: 'n4' },
  { character: '事', meaning: 'Thing / Matter', onyomi: 'ジ, ズ', kunyomi: 'こと, つか-う', mnemonic: 'A hand holding a brush cataloging items on a rack, recording events.', illustration: '💼', level: 'n4' },
  { character: '自', meaning: 'Self', onyomi: 'ジ, シ', kunyomi: 'みずか-ら', mnemonic: 'A representation of a nose, which Japanese people point to when referring to themselves.', illustration: '👤', level: 'n4' },
  { character: '発', meaning: 'Start / Depart / Emit', onyomi: 'ハツ, ホツ', kunyomi: 'た-つ, あば-く', mnemonic: 'Two feet walking outwards, launching a missile or starting a journey.', illustration: '🚀', level: 'n4' },
  { character: '者', meaning: 'Person (professional)', onyomi: 'シャ', kunyomi: 'もの', mnemonic: 'An old person (耂) speaking from a podium (日), representing a professional.', illustration: '🧑‍🎓', level: 'n4' },
  { character: '地', meaning: 'Earth / Ground', onyomi: 'チ, ジ', kunyomi: 'つち', mnemonic: 'Soil (土) next to a winding scorpion tail, representing land.', illustration: '🌍', level: 'n4' },
  { character: '業', meaning: 'Business / Industry', onyomi: 'ギョウ, ゴウ', kunyomi: 'わざ', mnemonic: 'A rack holding musical instruments or work files, symbolizing industry.', illustration: '🏭', level: 'n4' },
  { character: '方', meaning: 'Direction / Person (polite)', onyomi: 'ホウ', kunyomi: 'かた, -がた', mnemonic: 'A plow tool carving direction indicators into a field.', illustration: '🧭', level: 'n4' },
  { character: '新', meaning: 'New', onyomi: 'シン', kunyomi: 'あたら-しい, あら-た', mnemonic: 'Standing on a tree (親) with an axe (斤) cutting wood to make new items.', illustration: '🆕', level: 'n4' },
  { character: '場', meaning: 'Place / Spot', onyomi: 'ジョウ, チョウ', kunyomi: 'ば', mnemonic: 'Soil (土) under the sun (日) with waves of energy, showing an active place.', illustration: '📍', level: 'n4' },
  { character: '員', meaning: 'Employee / Member', onyomi: 'イン', kunyomi: 'かず', mnemonic: 'A mouth (口) on top of money/shells (貝), representing a paid staff member.', illustration: '🧑‍💼', level: 'n4' },
  { character: '立', meaning: 'Stand', onyomi: 'リツ, リュウ', kunyomi: 'た-つ, た-てる', mnemonic: 'A person standing upright on a flat base line.', illustration: '🧍', level: 'n4' },
  { character: '開', meaning: 'Open', onyomi: 'カイ', kunyomi: 'ひら-く, あ-く', mnemonic: 'Two hands lifting the crossbar (𠂡) of a gate (門) to open it.', illustration: '🔓', level: 'n4' },
  { character: '問', meaning: 'Question / Problem', onyomi: 'モン', kunyomi: 'と-う, と-い', mnemonic: 'A mouth (口) speaking questions through a gate (門).', illustration: '❓', level: 'n4' },
  { character: '代', meaning: 'Substitute / Generation / Fee', onyomi: 'ダイ, タイ', kunyomi: 'か-わる, よ', mnemonic: 'A person (亻) holding a stake, representing a temporary placeholder.', illustration: '🔄', level: 'n4' },
  { character: '明', meaning: 'Bright / Clear', onyomi: 'メイ, ミョウ', kunyomi: 'あか-るい, あき-らか', mnemonic: 'The sun (日) and the moon (月) shining together to make things bright.', illustration: '💡', level: 'n4' },
  { character: '動', meaning: 'Move', onyomi: 'ドウ', kunyomi: 'うご-く, うご-かす', mnemonic: 'A heavy object (重) moved by strong arm muscle power (力).', illustration: '🏃', level: 'n4' },
  { character: '京', meaning: 'Capital City', onyomi: 'キョウ, ケイ', kunyomi: 'みやこ', mnemonic: 'A large building standing high on top of a hill, denoting the capital.', illustration: '🗼', level: 'n4' },
  { character: '通', meaning: 'Pass Through / Commute', onyomi: 'ツウ, ツ', kunyomi: 'とお-る, かよ-う', mnemonic: 'A path (辶) going under a roofed tunnel, showing commuting passage.', illustration: '🛤️', level: 'n4' },
  { character: '言', meaning: 'Say / Word', onyomi: 'ゲン, ゴン', kunyomi: 'い-う, こと', mnemonic: 'Mouth (口) emitting four lines of speech, representing words.', illustration: '🗣️', level: 'n4' },
  { character: '理', meaning: 'Reason / Logic', onyomi: 'リ', kunyomi: 'ことわり', mnemonic: 'A king (王) carving logic lines inside a computer field (里).', illustration: '🧠', level: 'n4' },
  { character: '体', meaning: 'Body', onyomi: 'タイ, テイ', kunyomi: 'からだ', mnemonic: 'A person (亻) standing next to a tree (本), resting their physical body.', illustration: '🧍‍♂️', level: 'n4' },
  { character: '田', meaning: 'Rice Field', onyomi: 'デン', kunyomi: 'た', mnemonic: 'A square field divided into four smaller plots by dikes.', illustration: '🌾', level: 'n4' },
  { character: '主', meaning: 'Master / Main', onyomi: 'シュ, ス', kunyomi: 'ぬし, おも', mnemonic: 'A burning flame sitting on top of a candle stand, the master source of light.', illustration: '👑', level: 'n4' },
  { character: '題', meaning: 'Topic / Title / Problem', onyomi: 'ダイ', kunyomi: 'おだい', mnemonic: 'A key concept (是) written at the head (頁) of a document topic.', illustration: '📋', level: 'n4' },
  { character: '意', meaning: 'Idea / Mind / Intention', onyomi: 'イ', kunyomi: 'こころ', mnemonic: 'A sound (音) emerging from the heart (心) showing one\'s intentions.', illustration: '💭', level: 'n4' },
  { character: '不', meaning: 'Negative / Non- / Bad', onyomi: 'フ, ブ', kunyomi: 'ず', mnemonic: 'A plant seed failing to sprout, representing negation.', illustration: '❌', level: 'n4' },
  { character: '作', meaning: 'Make / Create', onyomi: 'サク, サ', kunyomi: 'つく-る', mnemonic: 'A person (亻) holding a knife carving out a new item.', illustration: '🛠️', level: 'n4' },
  { character: '用', meaning: 'Use / Service', onyomi: 'ヨウ', kunyomi: 'もち-いる', mnemonic: 'A barrel shape showing lines of utility and storage usage.', illustration: '🔧', level: 'n4' },
  { character: '度', meaning: 'Degree / Times / Occasion', onyomi: 'ド, ト, タク', kunyomi: 'たび, たか-る', mnemonic: 'A hand holding a measuring tool inside a cavern to take temperature degrees.', illustration: '🌡️', level: 'n4' },
  { character: '強', meaning: 'Strong', onyomi: 'キョウ, ゴウ', kunyomi: 'つよ-い, し-いる', mnemonic: 'A strong bow (弓) protecting a muscular insect from threats.', illustration: '🏋️', level: 'n4' },
  { character: '公', meaning: 'Public / Official', onyomi: 'コウ, ク', kunyomi: 'おおやけ', mnemonic: 'Dividing (八) and sharing private land (厶) with the public.', illustration: '🏛️', level: 'n4' },
  { character: '持', meaning: 'Hold / Carry', onyomi: 'ジ', kunyomi: 'も-つ', mnemonic: 'A hand (手 -> 扌) offering help at a Buddhist temple (寺).', illustration: '持', level: 'n4' },
  { character: '野', meaning: 'Field / Wild', onyomi: 'ヤ, ショ', kunyomi: 'の', mnemonic: 'A village (里) next to a tool, bordering wild fields.', illustration: '🏕️', level: 'n4' },
  { character: '以', meaning: 'By Means Of / Because', onyomi: 'イ', kunyomi: 'もっ-て', mnemonic: 'A person using a tool to plow starting from a boundary line.', illustration: '➡️', level: 'n4' },
  { character: '思', meaning: 'Think', onyomi: 'シ', kunyomi: 'おも-う', mnemonic: 'Connecting brain thoughts in the head field (田) to the heart (心).', illustration: '🤔', level: 'n4' },
  { character: '家', meaning: 'House / Family', onyomi: 'カ, ケ', kunyomi: 'いえ, や, うち', mnemonic: 'A pig (豕) kept safe inside a roofed house shelter.', illustration: '🏠', level: 'n4' },
  { character: '世', meaning: 'World / Generation', onyomi: 'セイ, セ, ソウ', kunyomi: 'よ', mnemonic: 'Three plants growing and branching out, marking 30 years or generations.', illustration: '🌐', level: 'n4' },
  { character: '多', meaning: 'Many / Much', onyomi: 'タ', kunyomi: 'おお-い, まさ-に', mnemonic: 'Two crescent moons (夕) stacked together showing many nights passing.', illustration: '📈', level: 'n4' },
  { character: '正', meaning: 'Correct / Right', onyomi: 'セイ, ショウ', kunyomi: 'ただ-しい, まさ', mnemonic: 'A foot stopping (止) right at the boundary line, representing correct behavior.', illustration: '✅', level: 'n4' },
  { character: '院', meaning: 'Institution / Hospital', onyomi: 'イン', kunyomi: 'おうち', mnemonic: 'A high wall structure protecting a hall (完) for patients/members.', illustration: '🏥', level: 'n4' },
  { character: '心', meaning: 'Heart / Mind', onyomi: 'シン', kunyomi: 'こころ', mnemonic: 'A drawing of the heart chambers and valves pumping blood.', illustration: '❤️', level: 'n4' },
  { character: '界', meaning: 'Boundary / World', onyomi: 'カイ', kunyomi: 'さかい', mnemonic: 'A field (田) sitting on top of boundaries showing separate worlds.', illustration: '🗺️', level: 'n4' },
  { character: '教', meaning: 'Teach / Religion', onyomi: 'キョウ', kunyomi: 'おし-える, おそ-わる', mnemonic: 'A child studying filial lines being guided by a teacher\'s hand.', illustration: '👨‍🏫', level: 'n4' },
  { character: '文', meaning: 'Literature / Sentence', onyomi: 'ブン, モン', kunyomi: 'ふみ, あや', mnemonic: 'A person with tattoos or decorations on their chest, showing culture.', illustration: '📝', level: 'n4' },
  { character: '元', meaning: 'Origin / Former / Source', onyomi: 'オム, ボン', kunyomi: 'もと', mnemonic: 'A human (儿) showing a prominent head lines, the source of thoughts.', illustration: '🔋', level: 'n4' },
  { character: '重', meaning: 'Heavy / Pile Up', onyomi: 'ジュウ, チョウ', kunyomi: 'お重-い', mnemonic: 'A heavy bag tied around a pole and standing on the ground.', illustration: '🏋️‍♂️', level: 'n4' },
  { character: '近', meaning: 'Near / Close', onyomi: 'キン, コン', kunyomi: 'ちか-い', mnemonic: 'An axe (斤) path (辶) making a shortcut, bringing locations near.', illustration: '📍', level: 'n4' },
  { character: '考', meaning: 'Consider / Think', onyomi: 'コウ', kunyomi: 'かんが-える', mnemonic: 'An old person (耂) resting their chin on their hand, deep in thought.', illustration: '🧐', level: 'n4' },
  { character: '画', meaning: 'Drawing / Stroke / Plan', onyomi: 'ガ, カク', kunyomi: 'えが-く, かく-する', mnemonic: 'A border framing a rice field drawing, outlining boundaries.', illustration: '🎨', level: 'n4' },
  { character: '海', meaning: 'Sea / Ocean', onyomi: 'カイ', kunyomi: 'うみ', mnemonic: 'Water (水 -> 氵) representing the ocean, the mother (毎) of all life.', illustration: '🌊', level: 'n4' },
  { character: '売', meaning: 'Sell', onyomi: 'バイ', kunyomi: 'う-る, う-れる', mnemonic: 'A person walking away from a shop counter after selling items.', illustration: '💰', level: 'n4' },
  { character: '知', meaning: 'Know / Wisdom', onyomi: 'チ', kunyomi: 'し-る', mnemonic: 'An arrow (矢) flying straight into a mouth (口), hitting knowledge target.', illustration: '💡', level: 'n4' },
  { character: '道', meaning: 'Road / Path / Way', onyomi: 'ドウ, トウ', kunyomi: 'みち', mnemonic: 'Following a head leader (首) along a road/path (辶).', illustration: '🛣️', level: 'n4' },
  { character: '集', meaning: 'Gather / Collect', onyomi: 'シュウ', kunyomi: 'あつ-まる, あつ-める', mnemonic: 'Three birds (隹) nesting together on top of a single tree (木).', illustration: '👥', level: 'n4' },
  { character: '別', meaning: 'Separate / Another', onyomi: 'ベツ', kunyomi: 'わか-れる', mnemonic: 'A knife (刂) separating bones to divide sections.', illustration: '別', level: 'n4' },
  { character: '物', meaning: 'Thing / Object', onyomi: 'ブツ, モツ', kunyomi: 'もの', mnemonic: 'A cow (牛) standing next to a flags representing individual objects.', illustration: '📦', level: 'n4' },
  { character: '使', meaning: 'Use / Messenger', onyomi: 'シ', kunyomi: 'つか-う', mnemonic: 'An official person (亻) carrying out an instruction using assets.', illustration: '使', level: 'n4' },
  { character: '品', meaning: 'Product / Goods', onyomi: 'ヒン, ホン', kunyomi: 'しな', mnemonic: 'Three boxes/containers showing piles of manufactured goods.', illustration: '📦', level: 'n4' },
  { character: '死', meaning: 'Death / Die', onyomi: 'シ', kunyomi: 'し-ぬ', mnemonic: 'A person kneeling down to bury a skeleton under the soil.', illustration: '💀', level: 'n4' },
  { character: '特', meaning: 'Special', onyomi: 'トク', kunyomi: 'とく-に', mnemonic: 'A sacred cow (牛) kept safe at a temple (寺) for special rituals.', illustration: '⭐', level: 'n4' },
  { character: '始', meaning: 'Begin / Start', onyomi: 'シ', kunyomi: 'はじ-める, はじ-まる', mnemonic: 'A woman (女) holding a mouth platform to begin speaking lines.', illustration: '▶️', level: 'n4' },
  { character: '朝', meaning: 'Morning', onyomi: 'チョウ', kunyomi: 'あさ', mnemonic: 'The sun rising behind weeds while the crescent moon (月) is still visible.', illustration: '🌅', level: 'n4' },
  { character: '終', meaning: 'End / Finish', onyomi: 'シュウ', kunyomi: 'お-わる, お-える', mnemonic: 'Tying a knot on a thread (糸) showing that winter/work has ended.', illustration: '🏁', level: 'n4' },
  { character: '台', meaning: 'Platform / Pedestal / Unit Counter', onyomi: 'ダイ, タイ', kunyomi: 'うてな', mnemonic: 'A mouth platform standing on support columns, representing a pedestal.', illustration: '📺', level: 'n4' },
  { character: '広', meaning: 'Wide / Spacious', onyomi: 'コウ', kunyomi: 'ひろ-い, ひろ-げる', mnemonic: 'A large shelter building showing a spacious interior.', illustration: '↔️', level: 'n4' },
  { character: '住', meaning: 'Live / Dwell', onyomi: 'ジュウ, ヂュウ', kunyomi: 'す-む, す-まう', mnemonic: 'A person (亻) finding their main candle flame (主), settling down to live.', illustration: '🏠', level: 'n4' },
  { character: '真', meaning: 'True / Reality / Pure', onyomi: 'シン', kunyomi: 'ま, まこと', mnemonic: 'An eye looking straight up at a perfect, true alignment grid.', illustration: '💯', level: 'n4' },
  { character: '有', meaning: 'Exist / Have / Possess', onyomi: 'ユウ, ウ', kunyomi: 'あ-る', mnemonic: 'A hand holding meat (月) representing possession/having.', illustration: '🤲', level: 'n4' },
  { character: '病', meaning: 'Illness / Sick', onyomi: 'ビョウ', kunyomi: 'や-む, やまい', mnemonic: 'A sick person inside a shelter (疒) suffering from third-degree heat.', illustration: '🤢', level: 'n4' },
  { character: '質', meaning: 'Quality / Matter / Inquiry', onyomi: 'シツ, シチ', kunyomi: 'たち, ただ-す', mnemonic: 'Two axes balancing coins/shells (貝) to assess their quality.', illustration: '💎', level: 'n4' },
  { character: '待', meaning: 'Wait', onyomi: 'タイ', kunyomi: 'ま-つ', mnemonic: 'A person walking (🚶) to wait at a temple gate (寺).', illustration: '⏳', level: 'n4' },
  { character: '旅', meaning: 'Trip / Travel', onyomi: 'リョ', kunyomi: 'たび', mnemonic: 'People gathering under a banner flag to start a travel tour.', illustration: '✈️', level: 'n4' },
  { character: '族', meaning: 'Tribe / Family', onyomi: 'ゾク', kunyomi: 'やから', mnemonic: 'People gather under a banner flag holding arrows to defend the family.', illustration: '👨‍👩‍👧‍👦', level: 'n4' },
  { character: '風', meaning: 'Wind / Style', onyomi: 'フウ, フ', kunyomi: 'かぜ, かざ-', mnemonic: 'Insects crawling under a banner showing waves of blowing wind.', illustration: '💨', level: 'n4' },
  { character: '切', meaning: 'Cut / Sharp', onyomi: 'セツ, サイ', kunyomi: 'き-る, ki-reru', mnemonic: 'A sharp knife (刀) slicing through the number seven (七).', illustration: '✂️', level: 'n4' },
  { character: '転', meaning: 'Revolve / Roll / Turn', onyomi: 'テン', kunyomi: 'ころ-がる, ころ-ぶ', mnemonic: 'A car (車) turning around a steam engine rising into rotation.', illustration: '🔄', level: 'n4' },
  { character: '薬', meaning: 'Medicine', onyomi: 'ヤク', kunyomi: 'くすり', mnemonic: 'Herbal grass (艹) that makes you happy and healthy (楽).', illustration: '💊', level: 'n4' },
  { character: '図', meaning: 'Map / Drawing / Plan', onyomi: 'ズ, ト', kunyomi: 'はか-る', mnemonic: 'An enclosed drawing/plan inside a map box boundary.', illustration: '🗺️', level: 'n4' },
  { character: '親', meaning: 'Parent / Intimate', onyomi: 'シン', kunyomi: 'おや, した-しい', mnemonic: 'A parent standing (立) on a tree (木) watching (見) over their child.', illustration: '👪', level: 'n4' },

  // Added N4 entries to reach 167:
  { character: '室', meaning: 'Room', onyomi: 'シツ', kunyomi: 'むろ', mnemonic: 'An arrow reaching its target under a roofed room structure.', illustration: '🚪', level: 'n4' },
  { character: '屋', meaning: 'Shop / House roof', onyomi: 'オク', kunyomi: 'や', mnemonic: 'A person arriving under a roofed house, showing a seller shop.', illustration: '🏪', level: 'n4' },
  { character: '鳥', meaning: 'Bird', onyomi: 'チョウ', kunyomi: 'とり', mnemonic: 'A drawing of a standing bird showing its head feathers, wing, and feet.', illustration: '🐦', level: 'n4' },
  { character: '魚', meaning: 'Fish', onyomi: 'ギョ', kunyomi: 'さかな, うお', mnemonic: 'A head, scaly body, and tail fins (灬) of a swimming fish.', illustration: '🐟', level: 'n4' },
  { character: '肉', meaning: 'Meat', onyomi: 'ニク', kunyomi: 'しし', mnemonic: 'Slices of meat cut from animal bones inside a shop window.', illustration: '🥩', level: 'n4' },
  { character: '茶', meaning: 'Tea', onyomi: 'チャ, サ', kunyomi: 'ちゃ', mnemonic: 'Herbs (艹) grown on trees (木) inside a wooden structure.', illustration: '🍵', level: 'n4' },
  { character: '酒', meaning: 'Alcohol / Sake', onyomi: 'シュ', kunyomi: 'さけ', mnemonic: 'Water droplets (氵) next to an aging fermentation jug (酉).', illustration: '🍶', level: 'n4' },
  { character: '湯', meaning: 'Hot Water / Bath', onyomi: 'トウ', kunyomi: 'ゆ', mnemonic: 'Water (氵) heating up under the sun (日) until it steams.', illustration: '♨️', level: 'n4' },
  { character: '宿', meaning: 'Inn / Hotel / Lodging', onyomi: 'シュク', kunyomi: 'やど', mnemonic: 'A person resting under a roof on a straw mat showing lodging.', illustration: '🏨', level: 'n4' },
  { character: '医', meaning: 'Doctor / Medical', onyomi: 'イ', kunyomi: 'い-する', mnemonic: 'An arrow (矢) enclosed in a box shelter, ready for medical use.', illustration: '👨‍⚕️', level: 'n4' },
  { character: '犬', meaning: 'Dog', onyomi: 'ケン', kunyomi: 'いぬ', mnemonic: 'A big person (大) carrying a small dot drop showing a loyal dog.', illustration: '🐕', level: 'n4' },
  { character: '猫', meaning: 'Cat', onyomi: 'ビョウ', kunyomi: 'ねこ', mnemonic: 'A wild beast animal chasing a seedling sprout inside a field.', illustration: '🐈', level: 'n4' },
  { character: '牛', meaning: 'Cow / Bull', onyomi: 'ギュウ', kunyomi: 'うし', mnemonic: 'A drawing of a cow\'s head showing horns and ears.', illustration: '🐄', level: 'n4' },
  { character: '羊', meaning: 'Sheep', onyomi: 'ヨウ', kunyomi: 'ひつじ', mnemonic: 'A drawing of a sheep\'s head with curling horns.', illustration: '🐑', level: 'n4' },
  { character: '馬', meaning: 'Horse', onyomi: 'バ', kunyomi: 'うま', mnemonic: 'A horse standing with four running legs (灬) and a flying mane.', illustration: '🐎', level: 'n4' },
  { character: '飯', meaning: 'Rice / Meal', onyomi: 'ハン', kunyomi: 'めし', mnemonic: 'Food (食) next to a person sitting down (反) to enjoy their meal.', illustration: '🍚', level: 'n4' },
  { character: '菜', meaning: 'Vegetable / Side dish', onyomi: 'サイ', kunyomi: 'な', mnemonic: 'Grass herbs (艹) plucked from a tree (木) with hands.', illustration: '🥗', level: 'n4' },
  { character: '園', meaning: 'Garden / Park', onyomi: 'エン', kunyomi: 'その', mnemonic: 'Beautiful flowers and paths enclosed inside a park boundary wall.', illustration: '🏡', level: 'n4' },
  { character: '森', meaning: 'Forest', onyomi: 'シン', kunyomi: 'もり', mnemonic: 'Three trees (木) grouped together, representing a dense forest.', illustration: '🌲', level: 'n4' },
  { character: '林', meaning: 'Woods / Grove', onyomi: 'リン', kunyomi: 'はやし', mnemonic: 'Two trees (木) standing side-by-side, representing woods.', illustration: '🌳', level: 'n4' },
  { character: '町', meaning: 'Town', onyomi: 'チョウ', kunyomi: 'まち', mnemonic: 'A street block next to a rice field (田).', illustration: '🏘️', level: 'n4' },
  { character: '村', meaning: 'Village', onyomi: 'ソン', kunyomi: 'むら', mnemonic: 'A cluster of wooden houses (tree 木) marked by a boundary post (寸).', illustration: '🏡', level: 'n4' },
  { character: '鉄', meaning: 'Iron / Steel', onyomi: 'テツ', kunyomi: 'くろがね', mnemonic: 'Metal gold (金) that is strong and black (失).', illustration: '🔗', level: 'n4' },
  { character: '門', meaning: 'Gate', onyomi: 'モン', kunyomi: 'かど', mnemonic: 'An outline of swinging double saloon-style gate doors.', illustration: '🚪', level: 'n4' },
  { character: '紙', meaning: 'Paper', onyomi: 'シ', kunyomi: 'かみ', mnemonic: 'Threads (糸) woven flat to make sheets of paper.', illustration: '📄', level: 'n4' },
  { character: '歌', meaning: 'Song / Sing', onyomi: 'カ', kunyomi: 'うた', mnemonic: 'A mouth (口) singing words next to a calligraphic notebook sheet.', illustration: '🎤', level: 'n4' },
  { character: '絵', meaning: 'Picture / Painting', onyomi: 'カイ, エ', kunyomi: 'え', mnemonic: 'Threads (糸) woven together to make a canvas block for a picture (会).', illustration: '🖼️', level: 'n4' },
  { character: '音', meaning: 'Sound', onyomi: 'オン, イン', kunyomi: 'おと, ね', mnemonic: 'A standing person (立) playing a mouth piece, making a sound.', illustration: '🔊', level: 'n4' },
  { character: '楽', meaning: 'Music / Comfort / Fun', onyomi: 'ラク, ガク', kunyomi: 'たの-しい', mnemonic: 'An instrument drum on a wooden stand (木) played for fun/music.', illustration: '🎵', level: 'n4' },
  { character: '味', meaning: 'Taste / Flavor', onyomi: 'ミ', kunyomi: 'あじ', mnemonic: 'A mouth (口) tasting the fresh foliage on a tree (未).', illustration: '👅', level: 'n4' },
  { character: '声', meaning: 'Voice', onyomi: 'セイ, ショウ', kunyomi: 'こえ', mnemonic: 'A sound emitted from a throat or hanging bell, representing a voice.', illustration: '🗣️', level: 'n4' },
  { character: '写', meaning: 'Copy / Photograph', onyomi: 'シャ', kunyomi: 'うつ-す', mnemonic: 'A cover over a document desk to trace and copy details.', illustration: '📷', level: 'n4' },
  { character: '送', meaning: 'Send', onyomi: 'ソウ', kunyomi: 'おく-る', mnemonic: 'Moving a parcel (辶) with hands (朕) to send it away.', illustration: '📦', level: 'n4' },
  { character: '急', meaning: 'Hurry / Urgent', onyomi: 'キュウ', kunyomi: 'いそ-ぐ', mnemonic: 'A fast-beating heart (心) inside a running person showing hurry.', illustration: '🏃‍♂️', level: 'n4' },
  { character: '低', meaning: 'Low', onyomi: 'テイ', kunyomi: 'ひく-い', mnemonic: 'A person (亻) bending down close to the floor line, showing low height.', illustration: '📉', level: 'n4' },
  { character: '暗', meaning: 'Dark', onyomi: 'アン', kunyomi: 'くら-い', mnemonic: 'The sun (日) covered by black sounds (音) making it dark.', illustration: '🌑', level: 'n4' },
  { character: '太', meaning: 'Fat / Thick', onyomi: 'タイ, タ', kunyomi: 'ふと-い', mnemonic: 'A big person (大) with an extra dot mark showing weight/girth.', illustration: '🍔', level: 'n4' },
  { character: '細', meaning: 'Thin / Narrow', onyomi: 'サイ', kunyomi: 'ほそ-い, こま-かい', mnemonic: 'A thread (糸) divided into tiny rice field partitions (田), showing thinness.', illustration: '🧵', level: 'n4' },
  { character: '弱', meaning: 'Weak', onyomi: 'ジャク', kunyomi: 'よわ-い', mnemonic: 'Two young bows (弓) with wings, showing they are not strong/weak.', illustration: '🥀', level: 'n4' },
  { character: '暑', meaning: 'Hot (weather)', onyomi: 'ショ', kunyomi: 'あつ-い', mnemonic: 'The sun (日) shining high over a populated site, making it hot.', illustration: '🥵', level: 'n4' },
  { character: '寒', meaning: 'Cold (weather)', onyomi: 'カン', kunyomi: 'さむ-い', mnemonic: 'A roof covering straw stacks frozen by blocks of ice (冫).', illustration: '🥶', level: 'n4' },
  { character: '悪', meaning: 'Bad / Evil', onyomi: 'アク, オ', kunyomi: 'わる-い', mnemonic: 'A heart (心) that has a cracked home structure (亜), representing bad.', illustration: '😈', level: 'n4' },
  { character: '走', meaning: 'Run', onyomi: 'ソウ', kunyomi: 'はし-る', mnemonic: 'A person stretching arms out above soil (土) lines, running.', illustration: '🏃', level: 'n4' },
  { character: '歩', meaning: 'Walk', onyomi: 'ホ, ブ', kunyomi: 'ある-く, あゆ-む', mnemonic: 'Taking steps forward (止) one foot after the other (少).', illustration: '🚶‍♂️', level: 'n4' },
  { character: '借', meaning: 'Borrow', onyomi: 'シャク', kunyomi: 'か-りる', mnemonic: 'A person (亻) borrowing money/documents from ancient times (昔).', illustration: '💸', level: 'n4' },
  { character: '貸', meaning: 'Lend', onyomi: 'タイ', kunyomi: 'か-す', mnemonic: 'Giving shell coins (貝) as a temporary replacement (代) to lend.', illustration: '🪙', level: 'n4' },
  { character: '返', meaning: 'Return', onyomi: 'ヘン', kunyomi: 'かえ-す, かえ-る', mnemonic: 'A path (辶) leading back to the stable, returning home.', illustration: '↩️', level: 'n4' },
  { character: '洗', meaning: 'Wash', onyomi: 'セン', kunyomi: 'あら-う', mnemonic: 'Water (氵) used to clean feet ahead (先) of entering.', illustration: '🧼', level: 'n4' },
  { character: '起', meaning: 'Wake Up / Get Up', onyomi: 'キ', kunyomi: 'お-きる, お-こす', mnemonic: 'Running (走) forward after waking up and standing (己).', illustration: '⏰', level: 'n4' },
  { character: '寝', meaning: 'Sleep', onyomi: 'シン', kunyomi: 'ね-る, ね-かす', mnemonic: 'A person resting under a roof on a bed next to clean sheets.', illustration: '🛌', level: 'n4' },
  { character: '仕', meaning: 'Serve / Official', onyomi: 'シ, ジ', kunyomi: 'つか-える', mnemonic: 'A person (亻) serving a samurai/official (士).', illustration: '🧑‍✈️', level: 'n4' },
  { character: '勉', meaning: 'Exert / Diligent', onyomi: 'ベン', kunyomi: 'つと-める', mnemonic: 'An escape effort using strong arm muscles (力), studying diligently.', illustration: '📝', level: 'n4' },
  { character: '春', meaning: 'Spring', onyomi: 'シュン', kunyomi: 'はる', mnemonic: 'Three people walking under the warm sun (日) in spring.', illustration: '🌱', level: 'n4' },
  { character: '夏', meaning: 'Summer', onyomi: 'カ, ゲ', kunyomi: 'なつ', mnemonic: 'A person walking slowly under the blazing sun, showing summer.', illustration: '☀️', level: 'n4' },
  { character: '秋', meaning: 'Autumn', onyomi: 'シュウ', kunyomi: 'あき', mnemonic: 'Grain crops (禾) turning red like fire (火) in autumn.', illustration: '🍁', level: 'n4' },
  { character: '冬', meaning: 'Winter', onyomi: 'トウ', kunyomi: 'ふゆ', mnemonic: 'Ice crystals (冫) forming at the end (夂) of the year, showing winter.', illustration: '❄️', level: 'n4' },
  { character: '館', meaning: 'Building / Hall', onyomi: 'カン', kunyomi: 'やかた', mnemonic: 'A public building where food (食) is served under high roofs.', illustration: '🏛️', level: 'n4' },
  { character: '堂', meaning: 'Hall / Temple', onyomi: 'ドウ', kunyomi: 'たか-どの', mnemonic: 'A spacious hall built high on soil (土) foundations.', illustration: '⛪', level: 'n4' },
  { character: '工', meaning: 'Craft / Construction', onyomi: 'コウ, ク', kunyomi: 'たくみ', mnemonic: 'An I-beam ruler representing engineering and craft work.', illustration: '🛠️', level: 'n4' },
  { character: '建', meaning: 'Build', onyomi: 'ケン, コン', kunyomi: 'た-てる, た-つ', mnemonic: 'Using brushes to outline a design, building high walls.', illustration: '🏗️', level: 'n4' },
  { character: '都', meaning: 'Metropolis / Capital', onyomi: 'ト, ツ', kunyomi: 'みやこ', mnemonic: 'A huge capital city with walls next to a regional center.', illustration: '🏙️', level: 'n4' },
  { character: '府', meaning: 'Government Office / Prefecture', onyomi: 'フ', kunyomi: 'おうち', mnemonic: 'A governmental shelter building storing public treasures.', illustration: '🏢', level: 'n4' },
  { character: '県', meaning: 'Prefecture', onyomi: 'ケン', kunyomi: 'か-ける', mnemonic: 'A head hanging upside down from a post, marking a provincial boundary.', illustration: '🗾', level: 'n4' },
  { character: '市', meaning: 'City / Market', onyomi: 'シ', kunyomi: 'いち', mnemonic: 'A flag standing over a market stand, showing a busy city center.', illustration: '🏙️', level: 'n4' },
  { character: '区', meaning: 'Ward / District', onyomi: 'ク', kunyomi: 'わき', mnemonic: 'A box partitioning areas of a city into district wards.', illustration: '🗺️', level: 'n4' },
  { character: '店', meaning: 'Shop', onyomi: 'テン', kunyomi: 'みせ, たな', mnemonic: 'A shelter building where goods are laid out for calculation.', illustration: '🏪', level: 'n4' },
  { character: '客', meaning: 'Guest / Customer', onyomi: 'キャク, カク', kunyomi: 'まろうど', mnemonic: 'A person arriving at a roofed home as a guest.', illustration: '👤', level: 'n4' },
  { character: '着', meaning: 'Wear / Arrive', onyomi: 'チャク, ジャク', kunyomi: 'き-る, つ-く', mnemonic: 'A sheep skin worn by a walking traveler arriving at a target.', illustration: '🧥', level: 'n4' },
  { character: '曜', meaning: 'Day of week', onyomi: 'ヨウ', kunyomi: 'ひかり', mnemonic: 'The sun (日) highlighting wings, telling the days of the week.', illustration: '📅', level: 'n4' },
  { character: '字', meaning: 'Character / Letter', onyomi: 'ジ', kunyomi: 'あざ, あざな', mnemonic: 'A child (子) under a roof studying letter characters.', illustration: '🔤', level: 'n4' },
  { character: '漢', meaning: 'Han / Chinese', onyomi: 'カン', kunyomi: 'から', mnemonic: 'Water flowing next to a dry grass field, representing the Han region.', illustration: '🇨🇳', level: 'n4' },
  { character: '英', meaning: 'English / Heroic', onyomi: 'エイ', kunyomi: 'はなぶさ', mnemonic: 'Grass growing over a central root, symbolizing English/heroic.', illustration: '🇬🇧', level: 'n4' },
  { character: '合', meaning: 'Fit / Match / Join', onyomi: 'ゴウ, ガッ', kunyomi: 'あ-う, あ-わす', mnemonic: 'A cover closing a box mouth (口) tightly to fit.', illustration: '🧩', level: 'n4' },
  { character: '私', meaning: 'I / Private', onyomi: 'シ', kunyomi: 'わたし, わたくし', mnemonic: 'A grain crop (禾) reserved for one\'s private (厶) use.', illustration: '🙋‍♂️', level: 'n4' },
  { character: '僕', meaning: 'I (male)', onyomi: 'ボク', kunyomi: 'しもべ', mnemonic: 'A male servant carrying out work tasks, used as "I" by males.', illustration: '🙋‍♂️', level: 'n4' },
  { character: '彼', meaning: 'He / Him', onyomi: 'ヒ', kunyomi: 'かれ, かの', mnemonic: 'A person walking along a path next to a skin ledger, pointing to "him".', illustration: '👨', level: 'n4' },
  { character: '説', meaning: 'Explain / Theory', onyomi: 'セツ', kunyomi: 'と-く', mnemonic: 'Speaking words (言) to describe items clearly, explaining a theory.', illustration: '🗣️', level: 'n4' },
  { character: '兄', meaning: 'Older Brother', onyomi: 'ケイ, キョウ', kunyomi: 'あに', mnemonic: 'A large mouth (口) on two legs speaking to lead younger siblings.', illustration: '👦', level: 'n4' },
  { character: '姉', meaning: 'Older Sister', onyomi: 'シ', kunyomi: 'あね', mnemonic: 'A woman (女) checking a market stand, leading the family as older sister.', illustration: '👧', level: 'n4' },
  { character: '弟', meaning: 'Younger Brother', onyomi: 'テイ, ダイ', kunyomi: 'おとうと', mnemonic: 'A leather strap wrapped around a post, following behind older brothers.', illustration: '👶', level: 'n4' },
  { character: '妹', meaning: 'Younger Sister', onyomi: 'マイ', kunyomi: 'いもうと', mnemonic: 'A young woman (女) next to a growing tree branch (未), younger sister.', illustration: '👧', level: 'n4' },
  { character: '夫', meaning: 'Husband', onyomi: 'フ, フウ', kunyomi: 'おっと', mnemonic: 'A man (大) wearing a hairpin showing he is married/husband.', illustration: '👨', level: 'n4' },
  { character: '妻', meaning: 'Wife', onyomi: 'サイ', kunyomi: 'つま', mnemonic: 'A woman with broom details in her hand, managing the home/wife.', illustration: '👩', level: 'n4' },
  { character: '頭', meaning: 'Head', onyomi: 'トウ, ズ', kunyomi: 'あたま, かしら', mnemonic: 'A bean (豆) shape next to page (頁) representing the head.', illustration: '👤', level: 'n4' },
  { character: '顔', meaning: 'Face', onyomi: 'ガン', kunyomi: 'かお', mnemonic: 'A head page (頁) showing features and expressions, the face.', illustration: '😀', level: 'n4' },
  { character: '首', meaning: 'Neck / Leader', onyomi: 'シュ', kunyomi: 'くび', mnemonic: 'A head outlining hair locks and eyes, sitting on the neck.', illustration: '🧣', level: 'n4' },
  { character: '指', meaning: 'Finger / Point', onyomi: 'シ', kunyomi: 'ゆび, さ-す', mnemonic: 'A hand (扌) pointing (旨) using a finger.', illustration: '👆', level: 'n4' },

  // ==================== DAILY LIFE KANJI (30 items) ====================
  { character: '喫', meaning: 'Consume / Sip / Smoke', onyomi: 'キツ', kunyomi: 'の-む', mnemonic: 'A mouth (口) eating contract details, as in 喫茶店 (cafe).', illustration: '☕', level: 'daily' },
  { character: '煙', meaning: 'Smoke', onyomi: 'エン', kunyomi: 'けむり', mnemonic: 'Fire (火) releasing dust particles through a stove, making smoke.', illustration: '💨', level: 'daily' },
  { character: '禁', meaning: 'Prohibit', onyomi: 'キン', kunyomi: 'とど-める', mnemonic: 'Sacred trees (林) inside a temple altar warning of prohibition.', illustration: '🚫', level: 'daily' },
  { character: '券', meaning: 'Ticket', onyomi: 'ケン', kunyomi: 'てがた', mnemonic: 'A knife (刀) cutting a document slip, representing a ticket.', illustration: '🎫', level: 'daily' },
  { character: '窓', meaning: 'Window', onyomi: 'ソウ', kunyomi: 'まど', mnemonic: 'A cave outline (穴) opening with a grill to serve as a window.', illustration: '🪟', level: 'daily' },
  { character: '濯', meaning: 'Rinse / Wash', onyomi: 'タク', kunyomi: 'すす-ぐ', mnemonic: 'Water (氵) cleaning feathers over a basin to rinse clothes.', illustration: '🧺', level: 'daily' },
  { character: '浴', meaning: 'Bathe', onyomi: 'ヨク', kunyomi: 'あ-びる', mnemonic: 'Water (氵) flowing down in a valley, representing a bath.', illustration: '🛁', level: 'daily' },
  { character: '便', meaning: 'Convenience / Mail', onyomi: 'ベン, ビン', kunyomi: 'たよ-り', mnemonic: 'A person (亻) carrying messages, bringing convenience.', illustration: '✉️', level: 'daily' },
  { character: '利', meaning: 'Benefit / Profit', onyomi: 'リ', kunyomi: 'き-く', mnemonic: 'Grain crops (禾) sliced by a sharp knife (刀) showing profits.', illustration: '📈', level: 'daily' },
  { character: '氷', meaning: 'Ice', onyomi: 'ヒョウ', kunyomi: 'こおり', mnemonic: 'Water (水) with an extra drop representing frozen ice.', illustration: '🧊', level: 'daily' },
  { character: '皿', meaning: 'Plate / Dish', onyomi: 'ベイ', kunyomi: 'さら', mnemonic: 'A flat container drawing representing a plate.', illustration: '🍽️', level: 'daily' },
  { character: '箸', meaning: 'Chopsticks', onyomi: 'チョ', kunyomi: 'はし', mnemonic: 'Bamboo (竹) sticks used to grab hot food next to a tree.', illustration: '🥢', level: 'daily' },
  { character: '塩', meaning: 'Salt', onyomi: 'エン', kunyomi: 'しお', mnemonic: 'Altar soil containing crystals monitored by officials, salt.', illustration: '🧂', level: 'daily' },
  { character: '糖', meaning: 'Sugar', onyomi: 'トウ', kunyomi: 'あめ', mnemonic: 'Rice grains (米) processed into sweet crystals, sugar.', illustration: '🍬', level: 'daily' },
  { character: '油', meaning: 'Oil', onyomi: 'ユ', kunyomi: 'あぶら', mnemonic: 'Water (氵) flowing from a squeezed seed jar, representing oil.', illustration: '🛢️', level: 'daily' },
  { character: '鍵', meaning: 'Key', onyomi: 'ケン', kunyomi: 'かぎ', mnemonic: 'Metal (金) cut into notches to build a lock key.', illustration: '🔑', level: 'daily' },
  { character: '鞄', meaning: 'Bag / Briefcase', onyomi: 'ホウ', kunyomi: 'かばん', mnemonic: 'Leather processed to wrap packages, representing a bag.', illustration: '👜', level: 'daily' },
  { character: '靴', meaning: 'Shoes', onyomi: 'カ', kunyomi: 'くつ', mnemonic: 'Leather wrapped around feet to walk, representing shoes.', illustration: '👟', level: 'daily' },
  { character: '服', meaning: 'Clothes / Obey', onyomi: 'フク', kunyomi: 'したが-う', mnemonic: 'A moon next to a kneeling person wrapping cloth around themselves.', illustration: '👕', level: 'daily' },
  { character: '畳', meaning: 'Tatami mat', onyomi: 'ジョウ', kunyomi: 'たたみ', mnemonic: 'Rice fields stacked flat to weave floor mats.', illustration: '🇯🇵', level: 'daily' },
  { character: '布', meaning: 'Cloth', onyomi: 'フ', kunyomi: 'ぬの', mnemonic: 'A hand holding a weaving frame, creating cloth.', illustration: '🧵', level: 'daily' },
  { character: '冷', meaning: 'Cold / Chilled', onyomi: 'レイ', kunyomi: 'つめ-たい, ひ-える', mnemonic: 'Ice crystals (冫) chilling an official building command.', illustration: '❄️', level: 'daily' },
  { character: '蔵', meaning: 'Storehouse', onyomi: 'ゾウ', kunyomi: 'くら', mnemonic: 'Herbs stored under a protective roof outline.', illustration: '🏢', level: 'daily' },
  { character: '庫', meaning: 'Warehouse / Garage', onyomi: 'コ, ク', kunyomi: 'くら', mnemonic: 'A carriage (車) parked inside a roofed storage warehouse.', illustration: '🏢', level: 'daily' },
  { character: '面', meaning: 'Face / Surface', onyomi: 'メン', kunyomi: 'おも, つら', mnemonic: 'A head boundary framing eyes and cheeks, the face.', illustration: '🎭', level: 'daily' },
  { character: '所', meaning: 'Place', onyomi: 'ショ', kunyomi: 'ところ', mnemonic: 'An axe (斤) cutting a door (戸) opening to mark a place.', illustration: '📍', level: 'daily' },
  { character: '箱', meaning: 'Box / Chest', onyomi: 'ソウ', kunyomi: 'はこ', mnemonic: 'Bamboo (竹) container used to store household goods (相), representing a box.', illustration: '📦', level: 'daily' },
  { character: '郵', meaning: 'Mail / Post Office', onyomi: 'ユウ', kunyomi: 'ゆう', mnemonic: 'Special mail courier delivering letters across borders.', illustration: '📮', level: 'daily' },
  { character: '宿', meaning: 'Lodging / Inn', onyomi: 'シュク', kunyomi: 'やど', mnemonic: 'A person sleeping under a roof on a straw mat.', illustration: '🏨', level: 'daily' },
  { character: '医', meaning: 'Doctor', onyomi: 'イ', kunyomi: 'い-する', mnemonic: 'An arrow inside a box, representing medical treatments.', illustration: '👨‍⚕️', level: 'daily' }
];
